backend:
  name: github
  repo: pavie-advocacia/PAVIE-091025
  branch: main
  base_url: https://blog.pavieadvocacia.com.br
  auth_endpoint: /api/auth/github-oauth
site_domain: blog.pavieadvocacia.com.br
media_folder: "public/uploads"
public_folder: "/uploads"
